title: Power Breakers DSC259R Final Project
description: A machine learning-driven analysis of U.S. power outage patterns and trends — uncovering what causes outages, when they happen, and who's most affected.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
url: "https://ajaganathan-coder.github.io/Power-Breakers/"